@startuml
class Application_interaction {
  Name
  Description
}
class Application_function {
  Name
  Description
}
class Application_process {
  Name
  Description
}
class Application_event {
  Name
  Description
}
class Application_service {
  Name
  Description
}
class ArchiMate_bendpoint {
}
class And_junction {
  Name
}
class Or_junction {
  Name
}
class Application_component {
  Name
  Description
}
class Application_collaboration {
  Name
  Description
}
class Application_interface {
  Name
  Description
}
class Data_object {
  Name
  Description
}
Application_collaboration "0..*" --> "0..*" Application_collaboration : Flow
Application_collaboration "0..*" --> "0..*" Application_component : Flow
Application_collaboration "0..*" --> "0..*" Application_event : Flow
Application_collaboration "0..*" --> "0..*" Application_function : Flow
Application_collaboration "0..*" --> "0..*" Application_interaction : Flow
Application_collaboration "0..*" --> "0..*" Application_interface : Flow
Application_collaboration "0..*" --> "0..*" Application_service : Flow
Application_collaboration "0..*" --> "0..*" And_junction : Flow
Application_collaboration "0..*" --> "0..*" Application_process : Flow
Application_collaboration "0..*" --> "0..*" Or_junction : Flow
Application_component "0..*" --> "0..*" Application_collaboration : Flow
Application_component "0..*" --> "0..*" Application_component : Flow
Application_component "0..*" --> "0..*" Application_event : Flow
Application_component "0..*" --> "0..*" Application_function : Flow
Application_component "0..*" --> "0..*" Application_interaction : Flow
Application_component "0..*" --> "0..*" Application_interface : Flow
Application_component "0..*" --> "0..*" Application_service : Flow
Application_component "0..*" --> "0..*" And_junction : Flow
Application_component "0..*" --> "0..*" Application_process : Flow
Application_component "0..*" --> "0..*" Or_junction : Flow
Application_event "0..*" --> "0..*" Application_collaboration : Flow
Application_event "0..*" --> "0..*" Application_component : Flow
Application_event "0..*" --> "0..*" Application_event : Flow
Application_event "0..*" --> "0..*" Application_function : Flow
Application_event "0..*" --> "0..*" Application_interaction : Flow
Application_event "0..*" --> "0..*" Application_interface : Flow
Application_event "0..*" --> "0..*" Application_service : Flow
Application_event "0..*" --> "0..*" And_junction : Flow
Application_event "0..*" --> "0..*" Application_process : Flow
Application_event "0..*" --> "0..*" Or_junction : Flow
Application_function "0..*" --> "0..*" Application_collaboration : Flow
Application_function "0..*" --> "0..*" Application_component : Flow
Application_function "0..*" --> "0..*" Application_event : Flow
Application_function "0..*" --> "0..*" Application_function : Flow
Application_function "0..*" --> "0..*" Application_interaction : Flow
Application_function "0..*" --> "0..*" Application_interface : Flow
Application_function "0..*" --> "0..*" Application_service : Flow
Application_function "0..*" --> "0..*" And_junction : Flow
Application_function "0..*" --> "0..*" Application_process : Flow
Application_function "0..*" --> "0..*" Or_junction : Flow
Application_interaction "0..*" --> "0..*" Application_collaboration : Flow
Application_interaction "0..*" --> "0..*" Application_component : Flow
Application_interaction "0..*" --> "0..*" Application_event : Flow
Application_interaction "0..*" --> "0..*" Application_function : Flow
Application_interaction "0..*" --> "0..*" Application_interaction : Flow
Application_interaction "0..*" --> "0..*" Application_interface : Flow
Application_interaction "0..*" --> "0..*" Application_service : Flow
Application_interaction "0..*" --> "0..*" And_junction : Flow
Application_interaction "0..*" --> "0..*" Application_process : Flow
Application_interaction "0..*" --> "0..*" Or_junction : Flow
Application_interface "0..*" --> "0..*" Application_collaboration : Flow
Application_interface "0..*" --> "0..*" Application_component : Flow
Application_interface "0..*" --> "0..*" Application_event : Flow
Application_interface "0..*" --> "0..*" Application_function : Flow
Application_interface "0..*" --> "0..*" Application_interaction : Flow
Application_interface "0..*" --> "0..*" Application_interface : Flow
Application_interface "0..*" --> "0..*" Application_service : Flow
Application_interface "0..*" --> "0..*" And_junction : Flow
Application_interface "0..*" --> "0..*" Application_process : Flow
Application_interface "0..*" --> "0..*" Or_junction : Flow
Application_process "0..*" --> "0..*" Application_collaboration : Flow
Application_process "0..*" --> "0..*" Application_component : Flow
Application_process "0..*" --> "0..*" Application_event : Flow
Application_process "0..*" --> "0..*" Application_function : Flow
Application_process "0..*" --> "0..*" Application_interaction : Flow
Application_process "0..*" --> "0..*" Application_interface : Flow
Application_process "0..*" --> "0..*" Application_service : Flow
Application_process "0..*" --> "0..*" And_junction : Flow
Application_process "0..*" --> "0..*" Application_process : Flow
Application_process "0..*" --> "0..*" Or_junction : Flow
Application_service "0..*" --> "0..*" Application_collaboration : Flow
Application_service "0..*" --> "0..*" Application_component : Flow
Application_service "0..*" --> "0..*" Application_event : Flow
Application_service "0..*" --> "0..*" Application_function : Flow
Application_service "0..*" --> "0..*" Application_interaction : Flow
Application_service "0..*" --> "0..*" Application_interface : Flow
Application_service "0..*" --> "0..*" Application_service : Flow
Application_service "0..*" --> "0..*" And_junction : Flow
Application_service "0..*" --> "0..*" Application_process : Flow
Application_service "0..*" --> "0..*" Or_junction : Flow
And_junction "0..*" --> "0..*" Application_collaboration : Flow
And_junction "0..*" --> "0..*" Application_component : Flow
And_junction "0..*" --> "0..*" Application_event : Flow
And_junction "0..*" --> "0..*" Application_function : Flow
And_junction "0..*" --> "0..*" Application_interaction : Flow
And_junction "0..*" --> "0..*" Application_interface : Flow
And_junction "0..*" --> "0..*" Application_service : Flow
And_junction "0..*" --> "0..*" And_junction : Flow
And_junction "0..*" --> "0..*" Application_process : Flow
And_junction "0..*" --> "0..*" Or_junction : Flow
Or_junction "0..*" --> "0..*" Application_collaboration : Flow
Or_junction "0..*" --> "0..*" Application_component : Flow
Or_junction "0..*" --> "0..*" Application_event : Flow
Or_junction "0..*" --> "0..*" Application_function : Flow
Or_junction "0..*" --> "0..*" Application_interaction : Flow
Or_junction "0..*" --> "0..*" Application_interface : Flow
Or_junction "0..*" --> "0..*" Application_service : Flow
Or_junction "0..*" --> "0..*" And_junction : Flow
Or_junction "0..*" --> "0..*" Application_process : Flow
Or_junction "0..*" --> "0..*" Or_junction : Flow
Application_collaboration "0..*" --> "0..*" Application_collaboration : Specialization
Application_collaboration "0..*" --> "0..*" Application_component : Specialization
Application_collaboration "0..*" --> "0..*" Data_object : Specialization
Application_collaboration "0..*" --> "0..*" Application_event : Specialization
Application_collaboration "0..*" --> "0..*" Application_function : Specialization
Application_collaboration "0..*" --> "0..*" Application_interaction : Specialization
Application_collaboration "0..*" --> "0..*" Application_interface : Specialization
Application_collaboration "0..*" --> "0..*" Application_process : Specialization
Application_collaboration "0..*" --> "0..*" Application_service : Specialization
Data_object "0..*" --> "0..*" Application_collaboration : Specialization
Data_object "0..*" --> "0..*" Application_component : Specialization
Data_object "0..*" --> "0..*" Data_object : Specialization
Data_object "0..*" --> "0..*" Application_event : Specialization
Data_object "0..*" --> "0..*" Application_function : Specialization
Data_object "0..*" --> "0..*" Application_interaction : Specialization
Data_object "0..*" --> "0..*" Application_interface : Specialization
Data_object "0..*" --> "0..*" Application_process : Specialization
Data_object "0..*" --> "0..*" Application_service : Specialization
Application_event "0..*" --> "0..*" Application_collaboration : Specialization
Application_event "0..*" --> "0..*" Application_component : Specialization
Application_event "0..*" --> "0..*" Data_object : Specialization
Application_event "0..*" --> "0..*" Application_event : Specialization
Application_event "0..*" --> "0..*" Application_function : Specialization
Application_event "0..*" --> "0..*" Application_interaction : Specialization
Application_event "0..*" --> "0..*" Application_interface : Specialization
Application_event "0..*" --> "0..*" Application_process : Specialization
Application_event "0..*" --> "0..*" Application_service : Specialization
Application_function "0..*" --> "0..*" Application_collaboration : Specialization
Application_function "0..*" --> "0..*" Application_component : Specialization
Application_function "0..*" --> "0..*" Data_object : Specialization
Application_function "0..*" --> "0..*" Application_event : Specialization
Application_function "0..*" --> "0..*" Application_function : Specialization
Application_function "0..*" --> "0..*" Application_interaction : Specialization
Application_function "0..*" --> "0..*" Application_interface : Specialization
Application_function "0..*" --> "0..*" Application_process : Specialization
Application_function "0..*" --> "0..*" Application_service : Specialization
Application_interaction "0..*" --> "0..*" Application_collaboration : Specialization
Application_interaction "0..*" --> "0..*" Application_component : Specialization
Application_interaction "0..*" --> "0..*" Data_object : Specialization
Application_interaction "0..*" --> "0..*" Application_event : Specialization
Application_interaction "0..*" --> "0..*" Application_function : Specialization
Application_interaction "0..*" --> "0..*" Application_interaction : Specialization
Application_interaction "0..*" --> "0..*" Application_interface : Specialization
Application_interaction "0..*" --> "0..*" Application_process : Specialization
Application_interaction "0..*" --> "0..*" Application_service : Specialization
Application_interface "0..*" --> "0..*" Application_collaboration : Specialization
Application_interface "0..*" --> "0..*" Application_component : Specialization
Application_interface "0..*" --> "0..*" Data_object : Specialization
Application_interface "0..*" --> "0..*" Application_event : Specialization
Application_interface "0..*" --> "0..*" Application_function : Specialization
Application_interface "0..*" --> "0..*" Application_interaction : Specialization
Application_interface "0..*" --> "0..*" Application_interface : Specialization
Application_interface "0..*" --> "0..*" Application_process : Specialization
Application_interface "0..*" --> "0..*" Application_service : Specialization
Application_process "0..*" --> "0..*" Application_collaboration : Specialization
Application_process "0..*" --> "0..*" Application_component : Specialization
Application_process "0..*" --> "0..*" Data_object : Specialization
Application_process "0..*" --> "0..*" Application_event : Specialization
Application_process "0..*" --> "0..*" Application_function : Specialization
Application_process "0..*" --> "0..*" Application_interaction : Specialization
Application_process "0..*" --> "0..*" Application_interface : Specialization
Application_process "0..*" --> "0..*" Application_process : Specialization
Application_process "0..*" --> "0..*" Application_service : Specialization
Application_service "0..*" --> "0..*" Application_collaboration : Specialization
Application_service "0..*" --> "0..*" Application_component : Specialization
Application_service "0..*" --> "0..*" Data_object : Specialization
Application_service "0..*" --> "0..*" Application_event : Specialization
Application_service "0..*" --> "0..*" Application_function : Specialization
Application_service "0..*" --> "0..*" Application_interaction : Specialization
Application_service "0..*" --> "0..*" Application_interface : Specialization
Application_service "0..*" --> "0..*" Application_process : Specialization
Application_service "0..*" --> "0..*" Application_service : Specialization
Application_component "0..*" --> "0..*" Application_collaboration : Specialization
Application_component "0..*" --> "0..*" Application_component : Specialization
Application_component "0..*" --> "0..*" Data_object : Specialization
Application_component "0..*" --> "0..*" Application_event : Specialization
Application_component "0..*" --> "0..*" Application_function : Specialization
Application_component "0..*" --> "0..*" Application_interaction : Specialization
Application_component "0..*" --> "0..*" Application_interface : Specialization
Application_component "0..*" --> "0..*" Application_process : Specialization
Application_component "0..*" --> "0..*" Application_service : Specialization
Application_collaboration "0..*" --> "0..*" Application_collaboration : Composition
Application_collaboration "0..*" --> "0..*" Application_component : Composition
Application_collaboration "0..*" --> "0..*" Application_event : Composition
Application_collaboration "0..*" --> "0..*" Application_function : Composition
Application_collaboration "0..*" --> "0..*" Application_interaction : Composition
Application_collaboration "0..*" --> "0..*" Application_interface : Composition
Application_collaboration "0..*" --> "0..*" Application_process : Composition
Application_collaboration "0..*" --> "0..*" Application_service : Composition
Application_collaboration "0..*" --> "0..*" ArchiMate_bendpoint : Composition
Application_collaboration "0..*" --> "0..*" Data_object : Composition
Application_component "0..*" --> "0..*" Application_collaboration : Composition
Application_component "0..*" --> "0..*" Application_component : Composition
Application_component "0..*" --> "0..*" Application_event : Composition
Application_component "0..*" --> "0..*" Application_function : Composition
Application_component "0..*" --> "0..*" Application_interaction : Composition
Application_component "0..*" --> "0..*" Application_interface : Composition
Application_component "0..*" --> "0..*" Application_process : Composition
Application_component "0..*" --> "0..*" Application_service : Composition
Application_component "0..*" --> "0..*" ArchiMate_bendpoint : Composition
Application_component "0..*" --> "0..*" Data_object : Composition
Data_object "0..*" --> "0..*" Application_collaboration : Composition
Data_object "0..*" --> "0..*" Application_component : Composition
Data_object "0..*" --> "0..*" Application_event : Composition
Data_object "0..*" --> "0..*" Application_function : Composition
Data_object "0..*" --> "0..*" Application_interaction : Composition
Data_object "0..*" --> "0..*" Application_interface : Composition
Data_object "0..*" --> "0..*" Application_process : Composition
Data_object "0..*" --> "0..*" Application_service : Composition
Data_object "0..*" --> "0..*" ArchiMate_bendpoint : Composition
Data_object "0..*" --> "0..*" Data_object : Composition
Application_event "0..*" --> "0..*" Application_collaboration : Composition
Application_event "0..*" --> "0..*" Application_component : Composition
Application_event "0..*" --> "0..*" Application_event : Composition
Application_event "0..*" --> "0..*" Application_function : Composition
Application_event "0..*" --> "0..*" Application_interaction : Composition
Application_event "0..*" --> "0..*" Application_interface : Composition
Application_event "0..*" --> "0..*" Application_process : Composition
Application_event "0..*" --> "0..*" Application_service : Composition
Application_event "0..*" --> "0..*" ArchiMate_bendpoint : Composition
Application_event "0..*" --> "0..*" Data_object : Composition
Application_function "0..*" --> "0..*" Application_collaboration : Composition
Application_function "0..*" --> "0..*" Application_component : Composition
Application_function "0..*" --> "0..*" Application_event : Composition
Application_function "0..*" --> "0..*" Application_function : Composition
Application_function "0..*" --> "0..*" Application_interaction : Composition
Application_function "0..*" --> "0..*" Application_interface : Composition
Application_function "0..*" --> "0..*" Application_process : Composition
Application_function "0..*" --> "0..*" Application_service : Composition
Application_function "0..*" --> "0..*" ArchiMate_bendpoint : Composition
Application_function "0..*" --> "0..*" Data_object : Composition
Application_interaction "0..*" --> "0..*" Application_collaboration : Composition
Application_interaction "0..*" --> "0..*" Application_component : Composition
Application_interaction "0..*" --> "0..*" Application_event : Composition
Application_interaction "0..*" --> "0..*" Application_function : Composition
Application_interaction "0..*" --> "0..*" Application_interaction : Composition
Application_interaction "0..*" --> "0..*" Application_interface : Composition
Application_interaction "0..*" --> "0..*" Application_process : Composition
Application_interaction "0..*" --> "0..*" Application_service : Composition
Application_interaction "0..*" --> "0..*" ArchiMate_bendpoint : Composition
Application_interaction "0..*" --> "0..*" Data_object : Composition
Application_interface "0..*" --> "0..*" Application_collaboration : Composition
Application_interface "0..*" --> "0..*" Application_component : Composition
Application_interface "0..*" --> "0..*" Application_event : Composition
Application_interface "0..*" --> "0..*" Application_function : Composition
Application_interface "0..*" --> "0..*" Application_interaction : Composition
Application_interface "0..*" --> "0..*" Application_interface : Composition
Application_interface "0..*" --> "0..*" Application_process : Composition
Application_interface "0..*" --> "0..*" Application_service : Composition
Application_interface "0..*" --> "0..*" ArchiMate_bendpoint : Composition
Application_interface "0..*" --> "0..*" Data_object : Composition
Application_service "0..*" --> "0..*" Application_collaboration : Composition
Application_service "0..*" --> "0..*" Application_component : Composition
Application_service "0..*" --> "0..*" Application_event : Composition
Application_service "0..*" --> "0..*" Application_function : Composition
Application_service "0..*" --> "0..*" Application_interaction : Composition
Application_service "0..*" --> "0..*" Application_interface : Composition
Application_service "0..*" --> "0..*" Application_process : Composition
Application_service "0..*" --> "0..*" Application_service : Composition
Application_service "0..*" --> "0..*" ArchiMate_bendpoint : Composition
Application_service "0..*" --> "0..*" Data_object : Composition
Application_process "0..*" --> "0..*" Application_collaboration : Composition
Application_process "0..*" --> "0..*" Application_component : Composition
Application_process "0..*" --> "0..*" Application_event : Composition
Application_process "0..*" --> "0..*" Application_function : Composition
Application_process "0..*" --> "0..*" Application_interaction : Composition
Application_process "0..*" --> "0..*" Application_interface : Composition
Application_process "0..*" --> "0..*" Application_process : Composition
Application_process "0..*" --> "0..*" Application_service : Composition
Application_process "0..*" --> "0..*" ArchiMate_bendpoint : Composition
Application_process "0..*" --> "0..*" Data_object : Composition
Application_collaboration "0..*" --> "0..*" Application_collaboration : Aggregation
Application_collaboration "0..*" --> "0..*" Application_component : Aggregation
Application_collaboration "0..*" --> "0..*" Data_object : Aggregation
Application_collaboration "0..*" --> "0..*" Application_event : Aggregation
Application_collaboration "0..*" --> "0..*" Application_function : Aggregation
Application_collaboration "0..*" --> "0..*" Application_interaction : Aggregation
Application_collaboration "0..*" --> "0..*" Application_process : Aggregation
Application_collaboration "0..*" --> "0..*" Application_service : Aggregation
Application_collaboration "0..*" --> "0..*" ArchiMate_bendpoint : Aggregation
Application_collaboration "0..*" --> "0..*" Application_interface : Aggregation
Application_component "0..*" --> "0..*" Application_collaboration : Aggregation
Application_component "0..*" --> "0..*" Application_component : Aggregation
Application_component "0..*" --> "0..*" Data_object : Aggregation
Application_component "0..*" --> "0..*" Application_event : Aggregation
Application_component "0..*" --> "0..*" Application_function : Aggregation
Application_component "0..*" --> "0..*" Application_interaction : Aggregation
Application_component "0..*" --> "0..*" Application_process : Aggregation
Application_component "0..*" --> "0..*" Application_service : Aggregation
Application_component "0..*" --> "0..*" ArchiMate_bendpoint : Aggregation
Application_component "0..*" --> "0..*" Application_interface : Aggregation
Data_object "0..*" --> "0..*" Application_collaboration : Aggregation
Data_object "0..*" --> "0..*" Application_component : Aggregation
Data_object "0..*" --> "0..*" Data_object : Aggregation
Data_object "0..*" --> "0..*" Application_event : Aggregation
Data_object "0..*" --> "0..*" Application_function : Aggregation
Data_object "0..*" --> "0..*" Application_interaction : Aggregation
Data_object "0..*" --> "0..*" Application_process : Aggregation
Data_object "0..*" --> "0..*" Application_service : Aggregation
Data_object "0..*" --> "0..*" ArchiMate_bendpoint : Aggregation
Data_object "0..*" --> "0..*" Application_interface : Aggregation
Application_event "0..*" --> "0..*" Application_collaboration : Aggregation
Application_event "0..*" --> "0..*" Application_component : Aggregation
Application_event "0..*" --> "0..*" Data_object : Aggregation
Application_event "0..*" --> "0..*" Application_event : Aggregation
Application_event "0..*" --> "0..*" Application_function : Aggregation
Application_event "0..*" --> "0..*" Application_interaction : Aggregation
Application_event "0..*" --> "0..*" Application_process : Aggregation
Application_event "0..*" --> "0..*" Application_service : Aggregation
Application_event "0..*" --> "0..*" ArchiMate_bendpoint : Aggregation
Application_event "0..*" --> "0..*" Application_interface : Aggregation
Application_function "0..*" --> "0..*" Application_collaboration : Aggregation
Application_function "0..*" --> "0..*" Application_component : Aggregation
Application_function "0..*" --> "0..*" Data_object : Aggregation
Application_function "0..*" --> "0..*" Application_event : Aggregation
Application_function "0..*" --> "0..*" Application_function : Aggregation
Application_function "0..*" --> "0..*" Application_interaction : Aggregation
Application_function "0..*" --> "0..*" Application_process : Aggregation
Application_function "0..*" --> "0..*" Application_service : Aggregation
Application_function "0..*" --> "0..*" ArchiMate_bendpoint : Aggregation
Application_function "0..*" --> "0..*" Application_interface : Aggregation
Application_interaction "0..*" --> "0..*" Application_collaboration : Aggregation
Application_interaction "0..*" --> "0..*" Application_component : Aggregation
Application_interaction "0..*" --> "0..*" Data_object : Aggregation
Application_interaction "0..*" --> "0..*" Application_event : Aggregation
Application_interaction "0..*" --> "0..*" Application_function : Aggregation
Application_interaction "0..*" --> "0..*" Application_interaction : Aggregation
Application_interaction "0..*" --> "0..*" Application_process : Aggregation
Application_interaction "0..*" --> "0..*" Application_service : Aggregation
Application_interaction "0..*" --> "0..*" ArchiMate_bendpoint : Aggregation
Application_interaction "0..*" --> "0..*" Application_interface : Aggregation
Application_interface "0..*" --> "0..*" Application_collaboration : Aggregation
Application_interface "0..*" --> "0..*" Application_component : Aggregation
Application_interface "0..*" --> "0..*" Data_object : Aggregation
Application_interface "0..*" --> "0..*" Application_event : Aggregation
Application_interface "0..*" --> "0..*" Application_function : Aggregation
Application_interface "0..*" --> "0..*" Application_interaction : Aggregation
Application_interface "0..*" --> "0..*" Application_process : Aggregation
Application_interface "0..*" --> "0..*" Application_service : Aggregation
Application_interface "0..*" --> "0..*" ArchiMate_bendpoint : Aggregation
Application_interface "0..*" --> "0..*" Application_interface : Aggregation
Application_process "0..*" --> "0..*" Application_collaboration : Aggregation
Application_process "0..*" --> "0..*" Application_component : Aggregation
Application_process "0..*" --> "0..*" Data_object : Aggregation
Application_process "0..*" --> "0..*" Application_event : Aggregation
Application_process "0..*" --> "0..*" Application_function : Aggregation
Application_process "0..*" --> "0..*" Application_interaction : Aggregation
Application_process "0..*" --> "0..*" Application_process : Aggregation
Application_process "0..*" --> "0..*" Application_service : Aggregation
Application_process "0..*" --> "0..*" ArchiMate_bendpoint : Aggregation
Application_process "0..*" --> "0..*" Application_interface : Aggregation
Application_service "0..*" --> "0..*" Application_collaboration : Aggregation
Application_service "0..*" --> "0..*" Application_component : Aggregation
Application_service "0..*" --> "0..*" Data_object : Aggregation
Application_service "0..*" --> "0..*" Application_event : Aggregation
Application_service "0..*" --> "0..*" Application_function : Aggregation
Application_service "0..*" --> "0..*" Application_interaction : Aggregation
Application_service "0..*" --> "0..*" Application_process : Aggregation
Application_service "0..*" --> "0..*" Application_service : Aggregation
Application_service "0..*" --> "0..*" ArchiMate_bendpoint : Aggregation
Application_service "0..*" --> "0..*" Application_interface : Aggregation
Application_collaboration "0..*" --> "0..*" Or_junction : Access_read/write
Application_collaboration "0..*" --> "0..*" And_junction : Access_read/write
Application_collaboration "0..*" --> "0..*" Data_object : Access_read/write
Application_process "0..*" --> "0..*" Or_junction : Access_read/write
Application_process "0..*" --> "0..*" And_junction : Access_read/write
Application_process "0..*" --> "0..*" Data_object : Access_read/write
Application_service "0..*" --> "0..*" Or_junction : Access_read/write
Application_service "0..*" --> "0..*" And_junction : Access_read/write
Application_service "0..*" --> "0..*" Data_object : Access_read/write
Application_component "0..*" --> "0..*" Or_junction : Access_read/write
Application_component "0..*" --> "0..*" And_junction : Access_read/write
Application_component "0..*" --> "0..*" Data_object : Access_read/write
Application_interaction "0..*" --> "0..*" Or_junction : Access_read/write
Application_interaction "0..*" --> "0..*" And_junction : Access_read/write
Application_interaction "0..*" --> "0..*" Data_object : Access_read/write
And_junction "0..*" --> "0..*" Or_junction : Access_read/write
And_junction "0..*" --> "0..*" And_junction : Access_read/write
And_junction "0..*" --> "0..*" Data_object : Access_read/write
Application_function "0..*" --> "0..*" Or_junction : Access_read/write
Application_function "0..*" --> "0..*" And_junction : Access_read/write
Application_function "0..*" --> "0..*" Data_object : Access_read/write
Application_event "0..*" --> "0..*" Or_junction : Access_read/write
Application_event "0..*" --> "0..*" And_junction : Access_read/write
Application_event "0..*" --> "0..*" Data_object : Access_read/write
Application_interface "0..*" --> "0..*" Or_junction : Access_read/write
Application_interface "0..*" --> "0..*" And_junction : Access_read/write
Application_interface "0..*" --> "0..*" Data_object : Access_read/write
Or_junction "0..*" --> "0..*" Or_junction : Access_read/write
Or_junction "0..*" --> "0..*" And_junction : Access_read/write
Or_junction "0..*" --> "0..*" Data_object : Access_read/write
Application_collaboration "0..*" --> "0..*" Or_junction : Access_write
Application_collaboration "0..*" --> "0..*" Data_object : Access_write
Application_collaboration "0..*" --> "0..*" And_junction : Access_write
Application_process "0..*" --> "0..*" Or_junction : Access_write
Application_process "0..*" --> "0..*" Data_object : Access_write
Application_process "0..*" --> "0..*" And_junction : Access_write
Application_service "0..*" --> "0..*" Or_junction : Access_write
Application_service "0..*" --> "0..*" Data_object : Access_write
Application_service "0..*" --> "0..*" And_junction : Access_write
Application_component "0..*" --> "0..*" Or_junction : Access_write
Application_component "0..*" --> "0..*" Data_object : Access_write
Application_component "0..*" --> "0..*" And_junction : Access_write
Or_junction "0..*" --> "0..*" Or_junction : Access_write
Or_junction "0..*" --> "0..*" Data_object : Access_write
Or_junction "0..*" --> "0..*" And_junction : Access_write
Application_interaction "0..*" --> "0..*" Or_junction : Access_write
Application_interaction "0..*" --> "0..*" Data_object : Access_write
Application_interaction "0..*" --> "0..*" And_junction : Access_write
And_junction "0..*" --> "0..*" Or_junction : Access_write
And_junction "0..*" --> "0..*" Data_object : Access_write
And_junction "0..*" --> "0..*" And_junction : Access_write
Application_function "0..*" --> "0..*" Or_junction : Access_write
Application_function "0..*" --> "0..*" Data_object : Access_write
Application_function "0..*" --> "0..*" And_junction : Access_write
Application_event "0..*" --> "0..*" Or_junction : Access_write
Application_event "0..*" --> "0..*" Data_object : Access_write
Application_event "0..*" --> "0..*" And_junction : Access_write
Application_interface "0..*" --> "0..*" Or_junction : Access_write
Application_interface "0..*" --> "0..*" Data_object : Access_write
Application_interface "0..*" --> "0..*" And_junction : Access_write
Application_collaboration "0..*" --> "0..*" Data_object : Access_read
Application_collaboration "0..*" --> "0..*" Or_junction : Access_read
Application_collaboration "0..*" --> "0..*" And_junction : Access_read
Application_process "0..*" --> "0..*" Data_object : Access_read
Application_process "0..*" --> "0..*" Or_junction : Access_read
Application_process "0..*" --> "0..*" And_junction : Access_read
Application_service "0..*" --> "0..*" Data_object : Access_read
Application_service "0..*" --> "0..*" Or_junction : Access_read
Application_service "0..*" --> "0..*" And_junction : Access_read
Or_junction "0..*" --> "0..*" Data_object : Access_read
Or_junction "0..*" --> "0..*" Or_junction : Access_read
Or_junction "0..*" --> "0..*" And_junction : Access_read
Application_interaction "0..*" --> "0..*" Data_object : Access_read
Application_interaction "0..*" --> "0..*" Or_junction : Access_read
Application_interaction "0..*" --> "0..*" And_junction : Access_read
And_junction "0..*" --> "0..*" Data_object : Access_read
And_junction "0..*" --> "0..*" Or_junction : Access_read
And_junction "0..*" --> "0..*" And_junction : Access_read
Application_function "0..*" --> "0..*" Data_object : Access_read
Application_function "0..*" --> "0..*" Or_junction : Access_read
Application_function "0..*" --> "0..*" And_junction : Access_read
Application_interface "0..*" --> "0..*" Data_object : Access_read
Application_interface "0..*" --> "0..*" Or_junction : Access_read
Application_interface "0..*" --> "0..*" And_junction : Access_read
Application_component "0..*" --> "0..*" Data_object : Access_read
Application_component "0..*" --> "0..*" Or_junction : Access_read
Application_component "0..*" --> "0..*" And_junction : Access_read
Application_event "0..*" --> "0..*" Data_object : Access_read
Application_event "0..*" --> "0..*" Or_junction : Access_read
Application_event "0..*" --> "0..*" And_junction : Access_read
Application_collaboration "0..*" --> "0..*" Application_event : Assignment
Application_collaboration "0..*" --> "0..*" Application_function : Assignment
Application_collaboration "0..*" --> "0..*" Application_interaction : Assignment
Application_collaboration "0..*" --> "0..*" Application_process : Assignment
Application_collaboration "0..*" --> "0..*" Application_service : Assignment
Application_collaboration "0..*" --> "0..*" And_junction : Assignment
Application_collaboration "0..*" --> "0..*" Or_junction : Assignment
Application_collaboration "0..*" --> "0..*" ArchiMate_bendpoint : Assignment
Application_component "0..*" --> "0..*" Application_event : Assignment
Application_component "0..*" --> "0..*" Application_function : Assignment
Application_component "0..*" --> "0..*" Application_interaction : Assignment
Application_component "0..*" --> "0..*" Application_process : Assignment
Application_component "0..*" --> "0..*" Application_service : Assignment
Application_component "0..*" --> "0..*" And_junction : Assignment
Application_component "0..*" --> "0..*" Or_junction : Assignment
Application_component "0..*" --> "0..*" ArchiMate_bendpoint : Assignment
Application_interface "0..*" --> "0..*" Application_event : Assignment
Application_interface "0..*" --> "0..*" Application_function : Assignment
Application_interface "0..*" --> "0..*" Application_interaction : Assignment
Application_interface "0..*" --> "0..*" Application_process : Assignment
Application_interface "0..*" --> "0..*" Application_service : Assignment
Application_interface "0..*" --> "0..*" And_junction : Assignment
Application_interface "0..*" --> "0..*" Or_junction : Assignment
Application_interface "0..*" --> "0..*" ArchiMate_bendpoint : Assignment
And_junction "0..*" --> "0..*" Application_event : Assignment
And_junction "0..*" --> "0..*" Application_function : Assignment
And_junction "0..*" --> "0..*" Application_interaction : Assignment
And_junction "0..*" --> "0..*" Application_process : Assignment
And_junction "0..*" --> "0..*" Application_service : Assignment
And_junction "0..*" --> "0..*" And_junction : Assignment
And_junction "0..*" --> "0..*" Or_junction : Assignment
And_junction "0..*" --> "0..*" ArchiMate_bendpoint : Assignment
Or_junction "0..*" --> "0..*" Application_event : Assignment
Or_junction "0..*" --> "0..*" Application_function : Assignment
Or_junction "0..*" --> "0..*" Application_interaction : Assignment
Or_junction "0..*" --> "0..*" Application_process : Assignment
Or_junction "0..*" --> "0..*" Application_service : Assignment
Or_junction "0..*" --> "0..*" And_junction : Assignment
Or_junction "0..*" --> "0..*" Or_junction : Assignment
Or_junction "0..*" --> "0..*" ArchiMate_bendpoint : Assignment
Application_collaboration "0..*" --> "0..*" Application_collaboration : Serving
Application_collaboration "0..*" --> "0..*" Application_component : Serving
Application_collaboration "0..*" --> "0..*" Application_event : Serving
Application_collaboration "0..*" --> "0..*" Application_function : Serving
Application_collaboration "0..*" --> "0..*" Application_interaction : Serving
Application_collaboration "0..*" --> "0..*" Application_interface : Serving
Application_collaboration "0..*" --> "0..*" Application_process : Serving
Application_collaboration "0..*" --> "0..*" Application_service : Serving
Application_collaboration "0..*" --> "0..*" And_junction : Serving
Application_collaboration "0..*" --> "0..*" Or_junction : Serving
Application_component "0..*" --> "0..*" Application_collaboration : Serving
Application_component "0..*" --> "0..*" Application_component : Serving
Application_component "0..*" --> "0..*" Application_event : Serving
Application_component "0..*" --> "0..*" Application_function : Serving
Application_component "0..*" --> "0..*" Application_interaction : Serving
Application_component "0..*" --> "0..*" Application_interface : Serving
Application_component "0..*" --> "0..*" Application_process : Serving
Application_component "0..*" --> "0..*" Application_service : Serving
Application_component "0..*" --> "0..*" And_junction : Serving
Application_component "0..*" --> "0..*" Or_junction : Serving
Application_event "0..*" --> "0..*" Application_collaboration : Serving
Application_event "0..*" --> "0..*" Application_component : Serving
Application_event "0..*" --> "0..*" Application_event : Serving
Application_event "0..*" --> "0..*" Application_function : Serving
Application_event "0..*" --> "0..*" Application_interaction : Serving
Application_event "0..*" --> "0..*" Application_interface : Serving
Application_event "0..*" --> "0..*" Application_process : Serving
Application_event "0..*" --> "0..*" Application_service : Serving
Application_event "0..*" --> "0..*" And_junction : Serving
Application_event "0..*" --> "0..*" Or_junction : Serving
Application_function "0..*" --> "0..*" Application_collaboration : Serving
Application_function "0..*" --> "0..*" Application_component : Serving
Application_function "0..*" --> "0..*" Application_event : Serving
Application_function "0..*" --> "0..*" Application_function : Serving
Application_function "0..*" --> "0..*" Application_interaction : Serving
Application_function "0..*" --> "0..*" Application_interface : Serving
Application_function "0..*" --> "0..*" Application_process : Serving
Application_function "0..*" --> "0..*" Application_service : Serving
Application_function "0..*" --> "0..*" And_junction : Serving
Application_function "0..*" --> "0..*" Or_junction : Serving
Application_interaction "0..*" --> "0..*" Application_collaboration : Serving
Application_interaction "0..*" --> "0..*" Application_component : Serving
Application_interaction "0..*" --> "0..*" Application_event : Serving
Application_interaction "0..*" --> "0..*" Application_function : Serving
Application_interaction "0..*" --> "0..*" Application_interaction : Serving
Application_interaction "0..*" --> "0..*" Application_interface : Serving
Application_interaction "0..*" --> "0..*" Application_process : Serving
Application_interaction "0..*" --> "0..*" Application_service : Serving
Application_interaction "0..*" --> "0..*" And_junction : Serving
Application_interaction "0..*" --> "0..*" Or_junction : Serving
Application_interface "0..*" --> "0..*" Application_collaboration : Serving
Application_interface "0..*" --> "0..*" Application_component : Serving
Application_interface "0..*" --> "0..*" Application_event : Serving
Application_interface "0..*" --> "0..*" Application_function : Serving
Application_interface "0..*" --> "0..*" Application_interaction : Serving
Application_interface "0..*" --> "0..*" Application_interface : Serving
Application_interface "0..*" --> "0..*" Application_process : Serving
Application_interface "0..*" --> "0..*" Application_service : Serving
Application_interface "0..*" --> "0..*" And_junction : Serving
Application_interface "0..*" --> "0..*" Or_junction : Serving
Application_process "0..*" --> "0..*" Application_collaboration : Serving
Application_process "0..*" --> "0..*" Application_component : Serving
Application_process "0..*" --> "0..*" Application_event : Serving
Application_process "0..*" --> "0..*" Application_function : Serving
Application_process "0..*" --> "0..*" Application_interaction : Serving
Application_process "0..*" --> "0..*" Application_interface : Serving
Application_process "0..*" --> "0..*" Application_process : Serving
Application_process "0..*" --> "0..*" Application_service : Serving
Application_process "0..*" --> "0..*" And_junction : Serving
Application_process "0..*" --> "0..*" Or_junction : Serving
Application_service "0..*" --> "0..*" Application_collaboration : Serving
Application_service "0..*" --> "0..*" Application_component : Serving
Application_service "0..*" --> "0..*" Application_event : Serving
Application_service "0..*" --> "0..*" Application_function : Serving
Application_service "0..*" --> "0..*" Application_interaction : Serving
Application_service "0..*" --> "0..*" Application_interface : Serving
Application_service "0..*" --> "0..*" Application_process : Serving
Application_service "0..*" --> "0..*" Application_service : Serving
Application_service "0..*" --> "0..*" And_junction : Serving
Application_service "0..*" --> "0..*" Or_junction : Serving
And_junction "0..*" --> "0..*" Application_collaboration : Serving
And_junction "0..*" --> "0..*" Application_component : Serving
And_junction "0..*" --> "0..*" Application_event : Serving
And_junction "0..*" --> "0..*" Application_function : Serving
And_junction "0..*" --> "0..*" Application_interaction : Serving
And_junction "0..*" --> "0..*" Application_interface : Serving
And_junction "0..*" --> "0..*" Application_process : Serving
And_junction "0..*" --> "0..*" Application_service : Serving
And_junction "0..*" --> "0..*" And_junction : Serving
And_junction "0..*" --> "0..*" Or_junction : Serving
Or_junction "0..*" --> "0..*" Application_collaboration : Serving
Or_junction "0..*" --> "0..*" Application_component : Serving
Or_junction "0..*" --> "0..*" Application_event : Serving
Or_junction "0..*" --> "0..*" Application_function : Serving
Or_junction "0..*" --> "0..*" Application_interaction : Serving
Or_junction "0..*" --> "0..*" Application_interface : Serving
Or_junction "0..*" --> "0..*" Application_process : Serving
Or_junction "0..*" --> "0..*" Application_service : Serving
Or_junction "0..*" --> "0..*" And_junction : Serving
Or_junction "0..*" --> "0..*" Or_junction : Serving
Application_collaboration "0..*" --> "0..*" Data_object : Access_undirected
Application_collaboration "0..*" --> "0..*" And_junction : Access_undirected
Application_collaboration "0..*" --> "0..*" Or_junction : Access_undirected
Application_component "0..*" --> "0..*" Data_object : Access_undirected
Application_component "0..*" --> "0..*" And_junction : Access_undirected
Application_component "0..*" --> "0..*" Or_junction : Access_undirected
Application_event "0..*" --> "0..*" Data_object : Access_undirected
Application_event "0..*" --> "0..*" And_junction : Access_undirected
Application_event "0..*" --> "0..*" Or_junction : Access_undirected
Application_function "0..*" --> "0..*" Data_object : Access_undirected
Application_function "0..*" --> "0..*" And_junction : Access_undirected
Application_function "0..*" --> "0..*" Or_junction : Access_undirected
Application_interaction "0..*" --> "0..*" Data_object : Access_undirected
Application_interaction "0..*" --> "0..*" And_junction : Access_undirected
Application_interaction "0..*" --> "0..*" Or_junction : Access_undirected
Application_interface "0..*" --> "0..*" Data_object : Access_undirected
Application_interface "0..*" --> "0..*" And_junction : Access_undirected
Application_interface "0..*" --> "0..*" Or_junction : Access_undirected
Application_service "0..*" --> "0..*" Data_object : Access_undirected
Application_service "0..*" --> "0..*" And_junction : Access_undirected
Application_service "0..*" --> "0..*" Or_junction : Access_undirected
And_junction "0..*" --> "0..*" Data_object : Access_undirected
And_junction "0..*" --> "0..*" And_junction : Access_undirected
And_junction "0..*" --> "0..*" Or_junction : Access_undirected
Application_process "0..*" --> "0..*" Data_object : Access_undirected
Application_process "0..*" --> "0..*" And_junction : Access_undirected
Application_process "0..*" --> "0..*" Or_junction : Access_undirected
Or_junction "0..*" --> "0..*" Data_object : Access_undirected
Or_junction "0..*" --> "0..*" And_junction : Access_undirected
Or_junction "0..*" --> "0..*" Or_junction : Access_undirected
Application_collaboration "0..*" --> "0..*" Application_collaboration : Realization
Application_collaboration "0..*" --> "0..*" Application_component : Realization
Application_collaboration "0..*" --> "0..*" Data_object : Realization
Application_collaboration "0..*" --> "0..*" Application_event : Realization
Application_collaboration "0..*" --> "0..*" Application_function : Realization
Application_collaboration "0..*" --> "0..*" Application_interaction : Realization
Application_collaboration "0..*" --> "0..*" Application_interface : Realization
Application_collaboration "0..*" --> "0..*" Application_process : Realization
Application_collaboration "0..*" --> "0..*" Application_service : Realization
Application_collaboration "0..*" --> "0..*" And_junction : Realization
Application_collaboration "0..*" --> "0..*" Or_junction : Realization
Application_collaboration "0..*" --> "0..*" ArchiMate_bendpoint : Realization
Application_component "0..*" --> "0..*" Application_collaboration : Realization
Application_component "0..*" --> "0..*" Application_component : Realization
Application_component "0..*" --> "0..*" Data_object : Realization
Application_component "0..*" --> "0..*" Application_event : Realization
Application_component "0..*" --> "0..*" Application_function : Realization
Application_component "0..*" --> "0..*" Application_interaction : Realization
Application_component "0..*" --> "0..*" Application_interface : Realization
Application_component "0..*" --> "0..*" Application_process : Realization
Application_component "0..*" --> "0..*" Application_service : Realization
Application_component "0..*" --> "0..*" And_junction : Realization
Application_component "0..*" --> "0..*" Or_junction : Realization
Application_component "0..*" --> "0..*" ArchiMate_bendpoint : Realization
Application_event "0..*" --> "0..*" Application_collaboration : Realization
Application_event "0..*" --> "0..*" Application_component : Realization
Application_event "0..*" --> "0..*" Data_object : Realization
Application_event "0..*" --> "0..*" Application_event : Realization
Application_event "0..*" --> "0..*" Application_function : Realization
Application_event "0..*" --> "0..*" Application_interaction : Realization
Application_event "0..*" --> "0..*" Application_interface : Realization
Application_event "0..*" --> "0..*" Application_process : Realization
Application_event "0..*" --> "0..*" Application_service : Realization
Application_event "0..*" --> "0..*" And_junction : Realization
Application_event "0..*" --> "0..*" Or_junction : Realization
Application_event "0..*" --> "0..*" ArchiMate_bendpoint : Realization
Application_function "0..*" --> "0..*" Application_collaboration : Realization
Application_function "0..*" --> "0..*" Application_component : Realization
Application_function "0..*" --> "0..*" Data_object : Realization
Application_function "0..*" --> "0..*" Application_event : Realization
Application_function "0..*" --> "0..*" Application_function : Realization
Application_function "0..*" --> "0..*" Application_interaction : Realization
Application_function "0..*" --> "0..*" Application_interface : Realization
Application_function "0..*" --> "0..*" Application_process : Realization
Application_function "0..*" --> "0..*" Application_service : Realization
Application_function "0..*" --> "0..*" And_junction : Realization
Application_function "0..*" --> "0..*" Or_junction : Realization
Application_function "0..*" --> "0..*" ArchiMate_bendpoint : Realization
Application_interaction "0..*" --> "0..*" Application_collaboration : Realization
Application_interaction "0..*" --> "0..*" Application_component : Realization
Application_interaction "0..*" --> "0..*" Data_object : Realization
Application_interaction "0..*" --> "0..*" Application_event : Realization
Application_interaction "0..*" --> "0..*" Application_function : Realization
Application_interaction "0..*" --> "0..*" Application_interaction : Realization
Application_interaction "0..*" --> "0..*" Application_interface : Realization
Application_interaction "0..*" --> "0..*" Application_process : Realization
Application_interaction "0..*" --> "0..*" Application_service : Realization
Application_interaction "0..*" --> "0..*" And_junction : Realization
Application_interaction "0..*" --> "0..*" Or_junction : Realization
Application_interaction "0..*" --> "0..*" ArchiMate_bendpoint : Realization
Application_interface "0..*" --> "0..*" Application_collaboration : Realization
Application_interface "0..*" --> "0..*" Application_component : Realization
Application_interface "0..*" --> "0..*" Data_object : Realization
Application_interface "0..*" --> "0..*" Application_event : Realization
Application_interface "0..*" --> "0..*" Application_function : Realization
Application_interface "0..*" --> "0..*" Application_interaction : Realization
Application_interface "0..*" --> "0..*" Application_interface : Realization
Application_interface "0..*" --> "0..*" Application_process : Realization
Application_interface "0..*" --> "0..*" Application_service : Realization
Application_interface "0..*" --> "0..*" And_junction : Realization
Application_interface "0..*" --> "0..*" Or_junction : Realization
Application_interface "0..*" --> "0..*" ArchiMate_bendpoint : Realization
Application_process "0..*" --> "0..*" Application_collaboration : Realization
Application_process "0..*" --> "0..*" Application_component : Realization
Application_process "0..*" --> "0..*" Data_object : Realization
Application_process "0..*" --> "0..*" Application_event : Realization
Application_process "0..*" --> "0..*" Application_function : Realization
Application_process "0..*" --> "0..*" Application_interaction : Realization
Application_process "0..*" --> "0..*" Application_interface : Realization
Application_process "0..*" --> "0..*" Application_process : Realization
Application_process "0..*" --> "0..*" Application_service : Realization
Application_process "0..*" --> "0..*" And_junction : Realization
Application_process "0..*" --> "0..*" Or_junction : Realization
Application_process "0..*" --> "0..*" ArchiMate_bendpoint : Realization
Application_service "0..*" --> "0..*" Application_collaboration : Realization
Application_service "0..*" --> "0..*" Application_component : Realization
Application_service "0..*" --> "0..*" Data_object : Realization
Application_service "0..*" --> "0..*" Application_event : Realization
Application_service "0..*" --> "0..*" Application_function : Realization
Application_service "0..*" --> "0..*" Application_interaction : Realization
Application_service "0..*" --> "0..*" Application_interface : Realization
Application_service "0..*" --> "0..*" Application_process : Realization
Application_service "0..*" --> "0..*" Application_service : Realization
Application_service "0..*" --> "0..*" And_junction : Realization
Application_service "0..*" --> "0..*" Or_junction : Realization
Application_service "0..*" --> "0..*" ArchiMate_bendpoint : Realization
And_junction "0..*" --> "0..*" Application_collaboration : Realization
And_junction "0..*" --> "0..*" Application_component : Realization
And_junction "0..*" --> "0..*" Data_object : Realization
And_junction "0..*" --> "0..*" Application_event : Realization
And_junction "0..*" --> "0..*" Application_function : Realization
And_junction "0..*" --> "0..*" Application_interaction : Realization
And_junction "0..*" --> "0..*" Application_interface : Realization
And_junction "0..*" --> "0..*" Application_process : Realization
And_junction "0..*" --> "0..*" Application_service : Realization
And_junction "0..*" --> "0..*" And_junction : Realization
And_junction "0..*" --> "0..*" Or_junction : Realization
And_junction "0..*" --> "0..*" ArchiMate_bendpoint : Realization
Or_junction "0..*" --> "0..*" Application_collaboration : Realization
Or_junction "0..*" --> "0..*" Application_component : Realization
Or_junction "0..*" --> "0..*" Data_object : Realization
Or_junction "0..*" --> "0..*" Application_event : Realization
Or_junction "0..*" --> "0..*" Application_function : Realization
Or_junction "0..*" --> "0..*" Application_interaction : Realization
Or_junction "0..*" --> "0..*" Application_interface : Realization
Or_junction "0..*" --> "0..*" Application_process : Realization
Or_junction "0..*" --> "0..*" Application_service : Realization
Or_junction "0..*" --> "0..*" And_junction : Realization
Or_junction "0..*" --> "0..*" Or_junction : Realization
Or_junction "0..*" --> "0..*" ArchiMate_bendpoint : Realization
Data_object "0..*" --> "0..*" Application_collaboration : Realization
Data_object "0..*" --> "0..*" Application_component : Realization
Data_object "0..*" --> "0..*" Data_object : Realization
Data_object "0..*" --> "0..*" Application_event : Realization
Data_object "0..*" --> "0..*" Application_function : Realization
Data_object "0..*" --> "0..*" Application_interaction : Realization
Data_object "0..*" --> "0..*" Application_interface : Realization
Data_object "0..*" --> "0..*" Application_process : Realization
Data_object "0..*" --> "0..*" Application_service : Realization
Data_object "0..*" --> "0..*" And_junction : Realization
Data_object "0..*" --> "0..*" Or_junction : Realization
Data_object "0..*" --> "0..*" ArchiMate_bendpoint : Realization
Application_collaboration "0..*" --> "0..*" Application_component : Association_undirected
Application_collaboration "0..*" --> "0..*" Data_object : Association_undirected
Application_collaboration "0..*" --> "0..*" Application_function : Association_undirected
Application_collaboration "0..*" --> "0..*" Application_interaction : Association_undirected
Application_collaboration "0..*" --> "0..*" Application_interface : Association_undirected
Application_collaboration "0..*" --> "0..*" Application_collaboration : Association_undirected
Application_collaboration "0..*" --> "0..*" Application_event : Association_undirected
Application_collaboration "0..*" --> "0..*" Application_process : Association_undirected
Application_collaboration "0..*" --> "0..*" Application_service : Association_undirected
Application_collaboration "0..*" --> "0..*" And_junction : Association_undirected
Application_collaboration "0..*" --> "0..*" Or_junction : Association_undirected
Application_collaboration "0..*" --> "0..*" ArchiMate_bendpoint : Association_undirected
Application_component "0..*" --> "0..*" Application_component : Association_undirected
Application_component "0..*" --> "0..*" Data_object : Association_undirected
Application_component "0..*" --> "0..*" Application_function : Association_undirected
Application_component "0..*" --> "0..*" Application_interaction : Association_undirected
Application_component "0..*" --> "0..*" Application_interface : Association_undirected
Application_component "0..*" --> "0..*" Application_collaboration : Association_undirected
Application_component "0..*" --> "0..*" Application_event : Association_undirected
Application_component "0..*" --> "0..*" Application_process : Association_undirected
Application_component "0..*" --> "0..*" Application_service : Association_undirected
Application_component "0..*" --> "0..*" And_junction : Association_undirected
Application_component "0..*" --> "0..*" Or_junction : Association_undirected
Application_component "0..*" --> "0..*" ArchiMate_bendpoint : Association_undirected
Data_object "0..*" --> "0..*" Application_component : Association_undirected
Data_object "0..*" --> "0..*" Data_object : Association_undirected
Data_object "0..*" --> "0..*" Application_function : Association_undirected
Data_object "0..*" --> "0..*" Application_interaction : Association_undirected
Data_object "0..*" --> "0..*" Application_interface : Association_undirected
Data_object "0..*" --> "0..*" Application_collaboration : Association_undirected
Data_object "0..*" --> "0..*" Application_event : Association_undirected
Data_object "0..*" --> "0..*" Application_process : Association_undirected
Data_object "0..*" --> "0..*" Application_service : Association_undirected
Data_object "0..*" --> "0..*" And_junction : Association_undirected
Data_object "0..*" --> "0..*" Or_junction : Association_undirected
Data_object "0..*" --> "0..*" ArchiMate_bendpoint : Association_undirected
Application_event "0..*" --> "0..*" Application_component : Association_undirected
Application_event "0..*" --> "0..*" Data_object : Association_undirected
Application_event "0..*" --> "0..*" Application_function : Association_undirected
Application_event "0..*" --> "0..*" Application_interaction : Association_undirected
Application_event "0..*" --> "0..*" Application_interface : Association_undirected
Application_event "0..*" --> "0..*" Application_collaboration : Association_undirected
Application_event "0..*" --> "0..*" Application_event : Association_undirected
Application_event "0..*" --> "0..*" Application_process : Association_undirected
Application_event "0..*" --> "0..*" Application_service : Association_undirected
Application_event "0..*" --> "0..*" And_junction : Association_undirected
Application_event "0..*" --> "0..*" Or_junction : Association_undirected
Application_event "0..*" --> "0..*" ArchiMate_bendpoint : Association_undirected
Application_interaction "0..*" --> "0..*" Application_component : Association_undirected
Application_interaction "0..*" --> "0..*" Data_object : Association_undirected
Application_interaction "0..*" --> "0..*" Application_function : Association_undirected
Application_interaction "0..*" --> "0..*" Application_interaction : Association_undirected
Application_interaction "0..*" --> "0..*" Application_interface : Association_undirected
Application_interaction "0..*" --> "0..*" Application_collaboration : Association_undirected
Application_interaction "0..*" --> "0..*" Application_event : Association_undirected
Application_interaction "0..*" --> "0..*" Application_process : Association_undirected
Application_interaction "0..*" --> "0..*" Application_service : Association_undirected
Application_interaction "0..*" --> "0..*" And_junction : Association_undirected
Application_interaction "0..*" --> "0..*" Or_junction : Association_undirected
Application_interaction "0..*" --> "0..*" ArchiMate_bendpoint : Association_undirected
Application_interface "0..*" --> "0..*" Application_component : Association_undirected
Application_interface "0..*" --> "0..*" Data_object : Association_undirected
Application_interface "0..*" --> "0..*" Application_function : Association_undirected
Application_interface "0..*" --> "0..*" Application_interaction : Association_undirected
Application_interface "0..*" --> "0..*" Application_interface : Association_undirected
Application_interface "0..*" --> "0..*" Application_collaboration : Association_undirected
Application_interface "0..*" --> "0..*" Application_event : Association_undirected
Application_interface "0..*" --> "0..*" Application_process : Association_undirected
Application_interface "0..*" --> "0..*" Application_service : Association_undirected
Application_interface "0..*" --> "0..*" And_junction : Association_undirected
Application_interface "0..*" --> "0..*" Or_junction : Association_undirected
Application_interface "0..*" --> "0..*" ArchiMate_bendpoint : Association_undirected
Application_process "0..*" --> "0..*" Application_component : Association_undirected
Application_process "0..*" --> "0..*" Data_object : Association_undirected
Application_process "0..*" --> "0..*" Application_function : Association_undirected
Application_process "0..*" --> "0..*" Application_interaction : Association_undirected
Application_process "0..*" --> "0..*" Application_interface : Association_undirected
Application_process "0..*" --> "0..*" Application_collaboration : Association_undirected
Application_process "0..*" --> "0..*" Application_event : Association_undirected
Application_process "0..*" --> "0..*" Application_process : Association_undirected
Application_process "0..*" --> "0..*" Application_service : Association_undirected
Application_process "0..*" --> "0..*" And_junction : Association_undirected
Application_process "0..*" --> "0..*" Or_junction : Association_undirected
Application_process "0..*" --> "0..*" ArchiMate_bendpoint : Association_undirected
Application_service "0..*" --> "0..*" Application_component : Association_undirected
Application_service "0..*" --> "0..*" Data_object : Association_undirected
Application_service "0..*" --> "0..*" Application_function : Association_undirected
Application_service "0..*" --> "0..*" Application_interaction : Association_undirected
Application_service "0..*" --> "0..*" Application_interface : Association_undirected
Application_service "0..*" --> "0..*" Application_collaboration : Association_undirected
Application_service "0..*" --> "0..*" Application_event : Association_undirected
Application_service "0..*" --> "0..*" Application_process : Association_undirected
Application_service "0..*" --> "0..*" Application_service : Association_undirected
Application_service "0..*" --> "0..*" And_junction : Association_undirected
Application_service "0..*" --> "0..*" Or_junction : Association_undirected
Application_service "0..*" --> "0..*" ArchiMate_bendpoint : Association_undirected
And_junction "0..*" --> "0..*" Application_component : Association_undirected
And_junction "0..*" --> "0..*" Data_object : Association_undirected
And_junction "0..*" --> "0..*" Application_function : Association_undirected
And_junction "0..*" --> "0..*" Application_interaction : Association_undirected
And_junction "0..*" --> "0..*" Application_interface : Association_undirected
And_junction "0..*" --> "0..*" Application_collaboration : Association_undirected
And_junction "0..*" --> "0..*" Application_event : Association_undirected
And_junction "0..*" --> "0..*" Application_process : Association_undirected
And_junction "0..*" --> "0..*" Application_service : Association_undirected
And_junction "0..*" --> "0..*" And_junction : Association_undirected
And_junction "0..*" --> "0..*" Or_junction : Association_undirected
And_junction "0..*" --> "0..*" ArchiMate_bendpoint : Association_undirected
Or_junction "0..*" --> "0..*" Application_component : Association_undirected
Or_junction "0..*" --> "0..*" Data_object : Association_undirected
Or_junction "0..*" --> "0..*" Application_function : Association_undirected
Or_junction "0..*" --> "0..*" Application_interaction : Association_undirected
Or_junction "0..*" --> "0..*" Application_interface : Association_undirected
Or_junction "0..*" --> "0..*" Application_collaboration : Association_undirected
Or_junction "0..*" --> "0..*" Application_event : Association_undirected
Or_junction "0..*" --> "0..*" Application_process : Association_undirected
Or_junction "0..*" --> "0..*" Application_service : Association_undirected
Or_junction "0..*" --> "0..*" And_junction : Association_undirected
Or_junction "0..*" --> "0..*" Or_junction : Association_undirected
Or_junction "0..*" --> "0..*" ArchiMate_bendpoint : Association_undirected
ArchiMate_bendpoint "0..*" --> "0..*" Application_component : Association_undirected
ArchiMate_bendpoint "0..*" --> "0..*" Data_object : Association_undirected
ArchiMate_bendpoint "0..*" --> "0..*" Application_function : Association_undirected
ArchiMate_bendpoint "0..*" --> "0..*" Application_interaction : Association_undirected
ArchiMate_bendpoint "0..*" --> "0..*" Application_interface : Association_undirected
ArchiMate_bendpoint "0..*" --> "0..*" Application_collaboration : Association_undirected
ArchiMate_bendpoint "0..*" --> "0..*" Application_event : Association_undirected
ArchiMate_bendpoint "0..*" --> "0..*" Application_process : Association_undirected
ArchiMate_bendpoint "0..*" --> "0..*" Application_service : Association_undirected
ArchiMate_bendpoint "0..*" --> "0..*" And_junction : Association_undirected
ArchiMate_bendpoint "0..*" --> "0..*" Or_junction : Association_undirected
ArchiMate_bendpoint "0..*" --> "0..*" ArchiMate_bendpoint : Association_undirected
Application_function "0..*" --> "0..*" Application_component : Association_undirected
Application_function "0..*" --> "0..*" Data_object : Association_undirected
Application_function "0..*" --> "0..*" Application_function : Association_undirected
Application_function "0..*" --> "0..*" Application_interaction : Association_undirected
Application_function "0..*" --> "0..*" Application_interface : Association_undirected
Application_function "0..*" --> "0..*" Application_collaboration : Association_undirected
Application_function "0..*" --> "0..*" Application_event : Association_undirected
Application_function "0..*" --> "0..*" Application_process : Association_undirected
Application_function "0..*" --> "0..*" Application_service : Association_undirected
Application_function "0..*" --> "0..*" And_junction : Association_undirected
Application_function "0..*" --> "0..*" Or_junction : Association_undirected
Application_function "0..*" --> "0..*" ArchiMate_bendpoint : Association_undirected
Application_collaboration "0..*" --> "0..*" Application_collaboration : Association_directed
Application_collaboration "0..*" --> "0..*" Application_component : Association_directed
Application_collaboration "0..*" --> "0..*" Data_object : Association_directed
Application_collaboration "0..*" --> "0..*" Application_event : Association_directed
Application_collaboration "0..*" --> "0..*" Application_function : Association_directed
Application_collaboration "0..*" --> "0..*" Application_interaction : Association_directed
Application_collaboration "0..*" --> "0..*" Application_interface : Association_directed
Application_collaboration "0..*" --> "0..*" Application_process : Association_directed
Application_collaboration "0..*" --> "0..*" Application_service : Association_directed
Application_collaboration "0..*" --> "0..*" And_junction : Association_directed
Application_collaboration "0..*" --> "0..*" Or_junction : Association_directed
Application_collaboration "0..*" --> "0..*" ArchiMate_bendpoint : Association_directed
Application_component "0..*" --> "0..*" Application_collaboration : Association_directed
Application_component "0..*" --> "0..*" Application_component : Association_directed
Application_component "0..*" --> "0..*" Data_object : Association_directed
Application_component "0..*" --> "0..*" Application_event : Association_directed
Application_component "0..*" --> "0..*" Application_function : Association_directed
Application_component "0..*" --> "0..*" Application_interaction : Association_directed
Application_component "0..*" --> "0..*" Application_interface : Association_directed
Application_component "0..*" --> "0..*" Application_process : Association_directed
Application_component "0..*" --> "0..*" Application_service : Association_directed
Application_component "0..*" --> "0..*" And_junction : Association_directed
Application_component "0..*" --> "0..*" Or_junction : Association_directed
Application_component "0..*" --> "0..*" ArchiMate_bendpoint : Association_directed
Data_object "0..*" --> "0..*" Application_collaboration : Association_directed
Data_object "0..*" --> "0..*" Application_component : Association_directed
Data_object "0..*" --> "0..*" Data_object : Association_directed
Data_object "0..*" --> "0..*" Application_event : Association_directed
Data_object "0..*" --> "0..*" Application_function : Association_directed
Data_object "0..*" --> "0..*" Application_interaction : Association_directed
Data_object "0..*" --> "0..*" Application_interface : Association_directed
Data_object "0..*" --> "0..*" Application_process : Association_directed
Data_object "0..*" --> "0..*" Application_service : Association_directed
Data_object "0..*" --> "0..*" And_junction : Association_directed
Data_object "0..*" --> "0..*" Or_junction : Association_directed
Data_object "0..*" --> "0..*" ArchiMate_bendpoint : Association_directed
Application_event "0..*" --> "0..*" Application_collaboration : Association_directed
Application_event "0..*" --> "0..*" Application_component : Association_directed
Application_event "0..*" --> "0..*" Data_object : Association_directed
Application_event "0..*" --> "0..*" Application_event : Association_directed
Application_event "0..*" --> "0..*" Application_function : Association_directed
Application_event "0..*" --> "0..*" Application_interaction : Association_directed
Application_event "0..*" --> "0..*" Application_interface : Association_directed
Application_event "0..*" --> "0..*" Application_process : Association_directed
Application_event "0..*" --> "0..*" Application_service : Association_directed
Application_event "0..*" --> "0..*" And_junction : Association_directed
Application_event "0..*" --> "0..*" Or_junction : Association_directed
Application_event "0..*" --> "0..*" ArchiMate_bendpoint : Association_directed
Application_function "0..*" --> "0..*" Application_collaboration : Association_directed
Application_function "0..*" --> "0..*" Application_component : Association_directed
Application_function "0..*" --> "0..*" Data_object : Association_directed
Application_function "0..*" --> "0..*" Application_event : Association_directed
Application_function "0..*" --> "0..*" Application_function : Association_directed
Application_function "0..*" --> "0..*" Application_interaction : Association_directed
Application_function "0..*" --> "0..*" Application_interface : Association_directed
Application_function "0..*" --> "0..*" Application_process : Association_directed
Application_function "0..*" --> "0..*" Application_service : Association_directed
Application_function "0..*" --> "0..*" And_junction : Association_directed
Application_function "0..*" --> "0..*" Or_junction : Association_directed
Application_function "0..*" --> "0..*" ArchiMate_bendpoint : Association_directed
Application_interaction "0..*" --> "0..*" Application_collaboration : Association_directed
Application_interaction "0..*" --> "0..*" Application_component : Association_directed
Application_interaction "0..*" --> "0..*" Data_object : Association_directed
Application_interaction "0..*" --> "0..*" Application_event : Association_directed
Application_interaction "0..*" --> "0..*" Application_function : Association_directed
Application_interaction "0..*" --> "0..*" Application_interaction : Association_directed
Application_interaction "0..*" --> "0..*" Application_interface : Association_directed
Application_interaction "0..*" --> "0..*" Application_process : Association_directed
Application_interaction "0..*" --> "0..*" Application_service : Association_directed
Application_interaction "0..*" --> "0..*" And_junction : Association_directed
Application_interaction "0..*" --> "0..*" Or_junction : Association_directed
Application_interaction "0..*" --> "0..*" ArchiMate_bendpoint : Association_directed
Application_process "0..*" --> "0..*" Application_collaboration : Association_directed
Application_process "0..*" --> "0..*" Application_component : Association_directed
Application_process "0..*" --> "0..*" Data_object : Association_directed
Application_process "0..*" --> "0..*" Application_event : Association_directed
Application_process "0..*" --> "0..*" Application_function : Association_directed
Application_process "0..*" --> "0..*" Application_interaction : Association_directed
Application_process "0..*" --> "0..*" Application_interface : Association_directed
Application_process "0..*" --> "0..*" Application_process : Association_directed
Application_process "0..*" --> "0..*" Application_service : Association_directed
Application_process "0..*" --> "0..*" And_junction : Association_directed
Application_process "0..*" --> "0..*" Or_junction : Association_directed
Application_process "0..*" --> "0..*" ArchiMate_bendpoint : Association_directed
Application_service "0..*" --> "0..*" Application_collaboration : Association_directed
Application_service "0..*" --> "0..*" Application_component : Association_directed
Application_service "0..*" --> "0..*" Data_object : Association_directed
Application_service "0..*" --> "0..*" Application_event : Association_directed
Application_service "0..*" --> "0..*" Application_function : Association_directed
Application_service "0..*" --> "0..*" Application_interaction : Association_directed
Application_service "0..*" --> "0..*" Application_interface : Association_directed
Application_service "0..*" --> "0..*" Application_process : Association_directed
Application_service "0..*" --> "0..*" Application_service : Association_directed
Application_service "0..*" --> "0..*" And_junction : Association_directed
Application_service "0..*" --> "0..*" Or_junction : Association_directed
Application_service "0..*" --> "0..*" ArchiMate_bendpoint : Association_directed
And_junction "0..*" --> "0..*" Application_collaboration : Association_directed
And_junction "0..*" --> "0..*" Application_component : Association_directed
And_junction "0..*" --> "0..*" Data_object : Association_directed
And_junction "0..*" --> "0..*" Application_event : Association_directed
And_junction "0..*" --> "0..*" Application_function : Association_directed
And_junction "0..*" --> "0..*" Application_interaction : Association_directed
And_junction "0..*" --> "0..*" Application_interface : Association_directed
And_junction "0..*" --> "0..*" Application_process : Association_directed
And_junction "0..*" --> "0..*" Application_service : Association_directed
And_junction "0..*" --> "0..*" And_junction : Association_directed
And_junction "0..*" --> "0..*" Or_junction : Association_directed
And_junction "0..*" --> "0..*" ArchiMate_bendpoint : Association_directed
Or_junction "0..*" --> "0..*" Application_collaboration : Association_directed
Or_junction "0..*" --> "0..*" Application_component : Association_directed
Or_junction "0..*" --> "0..*" Data_object : Association_directed
Or_junction "0..*" --> "0..*" Application_event : Association_directed
Or_junction "0..*" --> "0..*" Application_function : Association_directed
Or_junction "0..*" --> "0..*" Application_interaction : Association_directed
Or_junction "0..*" --> "0..*" Application_interface : Association_directed
Or_junction "0..*" --> "0..*" Application_process : Association_directed
Or_junction "0..*" --> "0..*" Application_service : Association_directed
Or_junction "0..*" --> "0..*" And_junction : Association_directed
Or_junction "0..*" --> "0..*" Or_junction : Association_directed
Or_junction "0..*" --> "0..*" ArchiMate_bendpoint : Association_directed
ArchiMate_bendpoint "0..*" --> "0..*" Application_collaboration : Association_directed
ArchiMate_bendpoint "0..*" --> "0..*" Application_component : Association_directed
ArchiMate_bendpoint "0..*" --> "0..*" Data_object : Association_directed
ArchiMate_bendpoint "0..*" --> "0..*" Application_event : Association_directed
ArchiMate_bendpoint "0..*" --> "0..*" Application_function : Association_directed
ArchiMate_bendpoint "0..*" --> "0..*" Application_interaction : Association_directed
ArchiMate_bendpoint "0..*" --> "0..*" Application_interface : Association_directed
ArchiMate_bendpoint "0..*" --> "0..*" Application_process : Association_directed
ArchiMate_bendpoint "0..*" --> "0..*" Application_service : Association_directed
ArchiMate_bendpoint "0..*" --> "0..*" And_junction : Association_directed
ArchiMate_bendpoint "0..*" --> "0..*" Or_junction : Association_directed
ArchiMate_bendpoint "0..*" --> "0..*" ArchiMate_bendpoint : Association_directed
Application_interface "0..*" --> "0..*" Application_collaboration : Association_directed
Application_interface "0..*" --> "0..*" Application_component : Association_directed
Application_interface "0..*" --> "0..*" Data_object : Association_directed
Application_interface "0..*" --> "0..*" Application_event : Association_directed
Application_interface "0..*" --> "0..*" Application_function : Association_directed
Application_interface "0..*" --> "0..*" Application_interaction : Association_directed
Application_interface "0..*" --> "0..*" Application_interface : Association_directed
Application_interface "0..*" --> "0..*" Application_process : Association_directed
Application_interface "0..*" --> "0..*" Application_service : Association_directed
Application_interface "0..*" --> "0..*" And_junction : Association_directed
Application_interface "0..*" --> "0..*" Or_junction : Association_directed
Application_interface "0..*" --> "0..*" ArchiMate_bendpoint : Association_directed
Application_collaboration "0..*" --> "0..*" Application_collaboration : Triggering
Application_collaboration "0..*" --> "0..*" Application_component : Triggering
Application_collaboration "0..*" --> "0..*" Application_event : Triggering
Application_collaboration "0..*" --> "0..*" Application_function : Triggering
Application_collaboration "0..*" --> "0..*" Application_interface : Triggering
Application_collaboration "0..*" --> "0..*" Application_process : Triggering
Application_collaboration "0..*" --> "0..*" Application_service : Triggering
Application_collaboration "0..*" --> "0..*" And_junction : Triggering
Application_collaboration "0..*" --> "0..*" Or_junction : Triggering
Application_collaboration "0..*" --> "0..*" Application_interaction : Triggering
Application_component "0..*" --> "0..*" Application_collaboration : Triggering
Application_component "0..*" --> "0..*" Application_component : Triggering
Application_component "0..*" --> "0..*" Application_event : Triggering
Application_component "0..*" --> "0..*" Application_function : Triggering
Application_component "0..*" --> "0..*" Application_interface : Triggering
Application_component "0..*" --> "0..*" Application_process : Triggering
Application_component "0..*" --> "0..*" Application_service : Triggering
Application_component "0..*" --> "0..*" And_junction : Triggering
Application_component "0..*" --> "0..*" Or_junction : Triggering
Application_component "0..*" --> "0..*" Application_interaction : Triggering
Application_event "0..*" --> "0..*" Application_collaboration : Triggering
Application_event "0..*" --> "0..*" Application_component : Triggering
Application_event "0..*" --> "0..*" Application_event : Triggering
Application_event "0..*" --> "0..*" Application_function : Triggering
Application_event "0..*" --> "0..*" Application_interface : Triggering
Application_event "0..*" --> "0..*" Application_process : Triggering
Application_event "0..*" --> "0..*" Application_service : Triggering
Application_event "0..*" --> "0..*" And_junction : Triggering
Application_event "0..*" --> "0..*" Or_junction : Triggering
Application_event "0..*" --> "0..*" Application_interaction : Triggering
Application_function "0..*" --> "0..*" Application_collaboration : Triggering
Application_function "0..*" --> "0..*" Application_component : Triggering
Application_function "0..*" --> "0..*" Application_event : Triggering
Application_function "0..*" --> "0..*" Application_function : Triggering
Application_function "0..*" --> "0..*" Application_interface : Triggering
Application_function "0..*" --> "0..*" Application_process : Triggering
Application_function "0..*" --> "0..*" Application_service : Triggering
Application_function "0..*" --> "0..*" And_junction : Triggering
Application_function "0..*" --> "0..*" Or_junction : Triggering
Application_function "0..*" --> "0..*" Application_interaction : Triggering
Application_interaction "0..*" --> "0..*" Application_collaboration : Triggering
Application_interaction "0..*" --> "0..*" Application_component : Triggering
Application_interaction "0..*" --> "0..*" Application_event : Triggering
Application_interaction "0..*" --> "0..*" Application_function : Triggering
Application_interaction "0..*" --> "0..*" Application_interface : Triggering
Application_interaction "0..*" --> "0..*" Application_process : Triggering
Application_interaction "0..*" --> "0..*" Application_service : Triggering
Application_interaction "0..*" --> "0..*" And_junction : Triggering
Application_interaction "0..*" --> "0..*" Or_junction : Triggering
Application_interaction "0..*" --> "0..*" Application_interaction : Triggering
Application_interface "0..*" --> "0..*" Application_collaboration : Triggering
Application_interface "0..*" --> "0..*" Application_component : Triggering
Application_interface "0..*" --> "0..*" Application_event : Triggering
Application_interface "0..*" --> "0..*" Application_function : Triggering
Application_interface "0..*" --> "0..*" Application_interface : Triggering
Application_interface "0..*" --> "0..*" Application_process : Triggering
Application_interface "0..*" --> "0..*" Application_service : Triggering
Application_interface "0..*" --> "0..*" And_junction : Triggering
Application_interface "0..*" --> "0..*" Or_junction : Triggering
Application_interface "0..*" --> "0..*" Application_interaction : Triggering
Application_service "0..*" --> "0..*" Application_collaboration : Triggering
Application_service "0..*" --> "0..*" Application_component : Triggering
Application_service "0..*" --> "0..*" Application_event : Triggering
Application_service "0..*" --> "0..*" Application_function : Triggering
Application_service "0..*" --> "0..*" Application_interface : Triggering
Application_service "0..*" --> "0..*" Application_process : Triggering
Application_service "0..*" --> "0..*" Application_service : Triggering
Application_service "0..*" --> "0..*" And_junction : Triggering
Application_service "0..*" --> "0..*" Or_junction : Triggering
Application_service "0..*" --> "0..*" Application_interaction : Triggering
And_junction "0..*" --> "0..*" Application_collaboration : Triggering
And_junction "0..*" --> "0..*" Application_component : Triggering
And_junction "0..*" --> "0..*" Application_event : Triggering
And_junction "0..*" --> "0..*" Application_function : Triggering
And_junction "0..*" --> "0..*" Application_interface : Triggering
And_junction "0..*" --> "0..*" Application_process : Triggering
And_junction "0..*" --> "0..*" Application_service : Triggering
And_junction "0..*" --> "0..*" And_junction : Triggering
And_junction "0..*" --> "0..*" Or_junction : Triggering
And_junction "0..*" --> "0..*" Application_interaction : Triggering
Or_junction "0..*" --> "0..*" Application_collaboration : Triggering
Or_junction "0..*" --> "0..*" Application_component : Triggering
Or_junction "0..*" --> "0..*" Application_event : Triggering
Or_junction "0..*" --> "0..*" Application_function : Triggering
Or_junction "0..*" --> "0..*" Application_interface : Triggering
Or_junction "0..*" --> "0..*" Application_process : Triggering
Or_junction "0..*" --> "0..*" Application_service : Triggering
Or_junction "0..*" --> "0..*" And_junction : Triggering
Or_junction "0..*" --> "0..*" Or_junction : Triggering
Or_junction "0..*" --> "0..*" Application_interaction : Triggering
Application_process "0..*" --> "0..*" Application_collaboration : Triggering
Application_process "0..*" --> "0..*" Application_component : Triggering
Application_process "0..*" --> "0..*" Application_event : Triggering
Application_process "0..*" --> "0..*" Application_function : Triggering
Application_process "0..*" --> "0..*" Application_interface : Triggering
Application_process "0..*" --> "0..*" Application_process : Triggering
Application_process "0..*" --> "0..*" Application_service : Triggering
Application_process "0..*" --> "0..*" And_junction : Triggering
Application_process "0..*" --> "0..*" Or_junction : Triggering
Application_process "0..*" --> "0..*" Application_interaction : Triggering
@enduml
